spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/books?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

  application:
    name: 03_restBook

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      file-size-threshold: 1KB # Files larger than 1KB will be written to disk
                

#logging:
#  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
#logging:
#  level:
#    org.springframework: INFO
#    org.hibernate: INFO