spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/SmartContactManager?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  application:
    name: 05_SmartContactManager

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      file-size-threshold: 1KB  # Files larger than 1KB will be written to disk
